apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-aug30-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-aug30-3 
  name: rag-aug30-3
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-aug30-3 
